### ISSUE TITLE
DeleteMultipleObjects return EOF

### ISSUE THREAD

**Issue by hewen1125** [baidubce/bce-sdk-go#3]
Delete success and bos api response return empty data. So  this function return EOF.

`func (r *BceResponse) ParseJsonBody(result interface{}) error {`
	`defer r.Body().Close()`
	`jsonDecoder := json.NewDecoder(r.Body())`
	`return jsonDecoder.Decode(result)`
`}`

**Comment by OshynSong** [comment]
res, err := client.DeleteMultipleObjects(...)
if err != nil {
    if err == io.EOF {
        fmt.Println("delete all")
    } else {
        fmt.Println("error occurs:", err)
    }
} else {
    fmt.Println("delete partial objects, not deleted:", res)
}

**Comment by hewen1125** [comment]
@OshynSong It can work but not a good idea.
